name: Central Sync Release

on:
  workflow_dispatch:
    inputs:
      stagedRepositoryId:
        description: "Staged repository id"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Request release promotion repo
    - uses: jvalkeal/nexus-sync@v0
      with:
        url: ${{ secrets.OSSRH_URL }}
        username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
        password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
        staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
        staging-repo-id: ${{ github.event.inputs.stagedRepositoryId }}
        release: true
