name: Labels Manage

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels-manage.yml'
      - '.github/workflows/label-manage.yml'
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mangle Labels
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels-manage.yml
          dry-run: false
          skip-delete: false
